#!/usr/bin/env python3
import os.path
import yaml
from jinja2 import Template


def load_config(path: str):
    """Loads a config file from a path)"""
    with open(path, 'r') as f:
        config = yaml.load(f, Loader=yaml.Loader)
    return config


def process_prop(prop, colors):
    if isinstance(prop, str):
        return colors[prop]
    else:  # must be dict, recurse
        return {k: process_prop(v, colors)
                for k, v in prop.items()}


def process_template(template_path, out_path, props):
    with open(template_path, 'r') as f:
        template = Template(f.read())
    out = template.render(props)
    with open(out_path, 'w') as f:
        f.write(out)


def main():
    config = load_config('leuven.yaml')
    colors = config['colors']
    props = process_prop(config['properties'], colors)
    props['colors'] = colors  # put that in there for convenience
    paths = [os.path.expanduser(p) for p in config['paths']]
    for path in paths:
        process_template(path + '.template', path, props)


if __name__ == '__main__':
    main()
